--[=[
	Copyright (c) 2025 Matthew (Creaco)
	All rights reserved.

	This software is licensed for use in Roblox experiences, personal or commercial.
	You may use and reference this module in your own projects. 
	
	You may not:
	• Redistribute this module, modified or unmodified
	• Publish derivative versions of this module
	• Claim authorship or ownership over this code

	For custom licenses, permissions, or integrations, contact the author.
--]=]

--!strict